export const PATHS = {
  // Auth
  LOGIN: "/",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_OTP: "/verify-otp",
  RESET_PASSWORD: "/reset-password",
  SUCCESS: "/success",

  // Dashboard
  DASHBOARD: "/dashboard",
  USER_MANAGEMENT: "/dashboard/users",
  STAFF_PROFILE: "/dashboard/users/staff",
  PATIENT_PROFILE: "/dashboard/users/patient",
  ADD_STAFF: "/dashboard/users/add-staff",
  ADD_PATIENT: "/dashboard/users/add-patient",
  EDIT_STAFF: "/dashboard/users/staff/edit",
  APPOINTMENTS: "/dashboard/appointments",
  DR_SCHEDULE: "/dashboard/dr-schedule",
  DOCTOR_SCHEDULE: "/dashboard/doctor-schedule",   // ← doctor's own schedule
  RADIOLOGY: "/dashboard/radiology",
  RADIOLOGY_PROFILE: "/dashboard/radiology/profile",   // ← RADIOLOGIST'S PROFILE
  RADIOLOGY_REQUESTS: "/dashboard/radiology/requests",
  RADIOLOGY_PATIENT_PROFILE: "/dashboard/radiology/patient/:patientId",
  RADIOLOGY_EXAM_ROOMS: "/dashboard/radiology/exam-rooms",
  RADIOLOGY_REPORTING: "/dashboard/radiology/reporting",
  RADIOLOGY_RESULTS: "/dashboard/radiology/results",
  RADIOLOGY_REVIEW_REPORT: "/dashboard/radiology/results/review/:queueId",
  RADIOLOGY_VIEW_EXAM: "/dashboard/radiology/view-exam/:id",
  RADIOLOGY_START_EXAM: "/dashboard/radiology/start-exam/:id",
  RADIOLOGY_SCAN: "/dashboard/radiology/scan/:id",
  RADIOLOGY_REPORT_DRAFT: "/dashboard/radiology/report-draft/:id",
  RADIOLOGY_FINAL_REPORT: "/dashboard/radiology/final-report/:id",
  LAB_CATALOG: "/dashboard/lab-catalog",
  LAB_TEST: "/dashboard/lab-test",
  LAB_TEST_REQUEST: "/dashboard/lab-test-request",
  CLINICS: "/dashboard/clinics",
  SETTINGS: "/dashboard/settings",
  PROFILE: "/dashboard/profile",
  PATIENT_VISIT: "/dashboard/patient-visit",
  RECEPTIONIST_PROFILE: "/dashboard/receptionist-profile",
  DOCTOR_VISITS: "/dashboard/doctor-visits",
  VISIT_DETAILS: "/dashboard/visit-details",
  NURSE_BOOK_LAB: "/dashboard/nurse/book-lab-appointment",
  NURSE_BOOK_RADIOLOGY: "/dashboard/nurse/book-radiology-appointment",
} as const;